name: Docker CI

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker
        shell: pwsh
        run: |
          docker version
          docker context show
          docker context use desktop-linux
          docker info

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ci-cd-test:latest .

      - name: Tag Docker image
        run: |
          docker tag ci-cd-test:latest ghcr.io/abcfgm/ci-cd-test:latest
          docker tag ci-cd-test:latest ghcr.io/abcfgm/ci-cd-test:sha-${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/abcfgm/ci-cd-test:latest
          docker push ghcr.io/abcfgm/ci-cd-test:sha-${{ github.sha }}

      - name: Deploy image
        shell: pwsh
        run: |
          $image = "ghcr.io/abcfgm/ci-cd-test:sha-${{ github.sha }}"

          docker pull $image

          docker rm -f ci-cd-test-deploy 2>$null

          docker run -d `
            --name ci-cd-test-deploy `
            -p 8080:8080 `
            $image

          Start-Sleep -Seconds 2

          docker ps

          docker logs ci-cd-test-deploy

          docker rm -f ci-cd-test-deploy