name: Docker CI

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ci-cd-test:latest .

      - name: Tag Docker image
        run: |
          docker tag ci-cd-test:latest ghcr.io/abcfgm/ci-cd-test:latest
          docker tag ci-cd-test:latest ghcr.io/abcfgm/ci-cd-test:sha-${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/abcfgm/ci-cd-test:latest
          docker push ghcr.io/abcfgm/ci-cd-test:sha-${{ github.sha }}